### ISSUE TITLE
Vấn đề về slide cần Fix

### ISSUE THREAD

**Issue by VinhDevNguyen** [VinhDevNguyen/Tensorflow_Seminar#2]
## Problem:
- Giải thích tại sao lại sử dụng `Conv2D`, `Flatten`
- Phân biệt giữa `Conv2D`, `conv3D` và `Conv1D`
- Tại sao lại phải sử dụng activation `Relu` cho lớp Conv2D

**Comment by dxv2k** [comment]
Dùng ReLU thay cho Sigmoid vì hiện tại ReLu cho kết quả tốt hơn: 
- ReLu không bị vấn đề "vanishing gradient" 
- Chi phí tính toán ReLU nhẹ hơn Sigmoid
- ReLu thể hiện convergence tốt hơn (http://www.cs.toronto.edu/~fritz/absps/imagenet.pdf)

Ref: https://stats.stackexchange.com/questions/126238/what-are-the-advantages-of-relu-over-sigmoid-function-in-deep-neural-networks#:~:text=The%20main%20reason%20why%20ReLu,it%20seems%20to%20work%20well.&text=In%20contrast%2C%20with%20ReLu%20activation,of%20the%20problems%20of%20sigmoid.

**Comment by VinhDevNguyen** [comment]
# Tại sao dùng Conv2D
2D convolution refers *not* to the dimension of the convolution kernel but to the dimension of the output. The output’s dimension is 2D, single channel. A single 2D convolution pass over a 3D image uses a 3D convolution kernal to obtain the 2D output
Ref [here](https://www.quora.com/Why-do-we-use-2D-convolution-for-RGB-images-which-are-in-fact-3D-data-cubes-Shouldnt-we-use-3D-convolution-for-RGB-and-4D-for-video)
